main{
  streaming:lighttpd;
  flvMask:http://[domain]/flvs/content/[id].flv;
  currentDomain:;
  useSecure:false;
  autoPlay:false;
  bufferTime:0;
  siteCallback:true;
  domains:site.com;
  defaultVideo:;
  seekingParamater:?fs=;
  storeSettings:true;
  windowFocus:false;
  allowStoreSettings:false;
  }
rtmp{
  conn:;
  }
ads{
  showPre:false;
  showPause:false;
  showPost:true;
  showPreroll:;
  showPostroll:false;
  }
ads.rolls.preroll{
  type:adfeed;
  url:http://ads.traffichaus.com/scripts/21037/preroll.php;
  }
ads.rolls.postroll{
  type:;
  url:;
  }
ads.display.pre{
  type:image;
  url:http://syndication.globaltraffico.com/adserve/index.php?z=153;
  }
ads.display.pause{
  type:image;
  url:http://syndication.globaltraffico.com/adserve/index.php?z=153;
  }
ads.display.post{
  type:image;
  url:http://syndication.globaltraffico.com/adserve/index.php?z=153;
  }
modules{
  load:[ChapterPreview, BitrateSwitcher];
  }
modules.ChapterPreview{
  url: http://cdne.pics.yjcontentdelivery.com/preview/c/0/a/c0a19015b8c886c2e9a5633a307c301e1433209065-640-480-1801-h264.flv-%d.jpg;
  delay:0;
  width:146;
  height:110;
  preload:true;
  step:30;
  showBackground:true;
  showTimeCode:true;
  fadeDuration:0;
  enabled:1;
  }
modules.InlineAd.colors{
  by:0x000000;
  title:0xFFFFFF;
  desc:0xFFFFFF;
  link:0xE0E0E0;
  }
modules.InlineAd.text{
  by:;
  title:Free Porn;
  desc:Check here for More FREE Porn;
  link:http://www.xtv.com;
  bottom:An example ad;
  }
  modules.InlineAd{time:1;useExternal:true;font:Verdana;}
enhancements{
  load:[ControlBar,Player];
  }
enhancements.Video{
  useFullHeight:false;
  maxWidth:false;
  displayClick:true;
  }
enhancements.ControlBar{
  useAutoHide:false;
  useProgressiveTimer:true;
  maxHeight:30;
  moveVideoControlsToTop:false;
  }
enhancements.ControlBar.autohide{
  fadeDuration:1;
  peakDuration:1;
  hide:true;
  fade:true;
  }
enhancements.ControlBar.seek{
  mouse:true;
  keyboard:true;
  keyRatio:2;
  stepSeekTime:5;
  onlySectionCached:false;
  realTime:true;
  }
enhancements.Player{
  maxWidth:false;
  keyboardFullScreen:true;
  showRelatedVideos:false;
  enableDimMode:true;
  }
enhancements.Player.dim{
  areas:[left,right,top,bottom];
  leftOpacity:80;
  rightOpacity:80;
  topOpacity:80;
  bottomOpacity:80;
  backgroundColor:#FF0000;
  }
ui{
  background:0x000000;
  downloadbar:true;
  showMiddlePlayOnPause:false;
  liveSeeking:true;
  }
ui.overlay{
  fullHeight:true;
  }
ui.rightclick.1{
  setting:link;
  display:YouJizz.Com - The Worlds Best Porn Site;
  target:_self;
  sepratorBefore:false;
  action:url;
  }
ui.watermarks{
  showWatermark:false;
  alwaysShowWatermark:false;
  }
ui.watermarks.display.domain{
  useNats:false;
  link:link;
  target:_blank;
  paddingLeft:0;
  opacity:100;
  paddingRight:0;
  url:/gfx_new/yjlogo.png;
  paddingTop:0;
  paddingBottom:0;
  placement:BL;
  }
ui.video{
  smoothing:true;
  defaultSize:FIT_SCREEN;
  }
ui.video.display{
  disableBufferView:true;
  removeBackgroundFill:true;
  floodFill:false;
  displayClick:true;
  }
ui.skin{
  file:/younoob_v2_skin_prev4.swf;
  useColors:false;
  }
modules.BitrateSwitcher{
  enabled: false;
  bitrates:[];
  labels:[];
  defaultBitrate:;
  defaultLabel:;
  }
modules.Embed{
  enabled:false;
  }